#--
# DO NOT MODIFY!!!!
# This file is automatically generated by rex 1.0.5
# from lexical definition file "compiler.rex".
#++

require 'racc/parser'
class CompilerLanguage < Racc::Parser
  require 'strscan'

  class ScanError < StandardError ; end

  attr_reader   :lineno
  attr_reader   :filename
  attr_accessor :state

  def scan_setup(str)
    @ss = StringScanner.new(str)
    @lineno =  1
    @state  = nil
  end

  def action
    yield
  end

  def scan_str(str)
    scan_setup(str)
    do_parse
  end
  alias :scan :scan_str

  def load_file( filename )
    @filename = filename
    open(filename, "r") do |f|
      scan_setup(f.read)
    end
  end

  def scan_file( filename )
    load_file(filename)
    do_parse
  end


  def next_token
    return if @ss.eos?
    
    # skips empty actions
    until token = _next_token or @ss.eos?; end
    token
  end

  def _next_token
    text = @ss.peek(1)
    @lineno  +=  1  if text == "\n"
    token = case @state
    when nil
      case
      when (text = @ss.scan(/[ \t]+/))
         action {} #no action

      when (text = @ss.scan(/\/\/.*/))
         action {} # no action

      when (text = @ss.scan(/\d+/))
         action { [:NUMBER, text.to_i] }

      when (text = @ss.scan(/if/))
         action { [:IF, text]}

      when (text = @ss.scan(/else/))
         action { [:ELSE, text]}

      when (text = @ss.scan(/return/))
         action { [:RETURN, text] }

      when (text = @ss.scan(/[(]/))
         action { [:OPENPAREN, text] }

      when (text = @ss.scan(/[)]/))
         action { [:CLOSEPAREN, text] }

      when (text = @ss.scan(/[{]/))
         action { [:OPENBRACE, text] }

      when (text = @ss.scan(/[}]/))
         action { [:CLOSEBRACE, text] }

      when (text = @ss.scan(/<<|>>|\-|\+|\*|\/|\=\=|<\=|>\=|\!\=|<|>/))
         action { [:OP, text]}

      when (text = @ss.scan(/[=]/))
         action { [:EQUALS, text] }

      when (text = @ss.scan(/const/))
         action { [:CONST, text] }

      when (text = @ss.scan(/int/))
         action { [:INT, text] }

      when (text = @ss.scan(/[,]/))
         action { [:COMMA, text] }

      when (text = @ss.scan(/[;]/))
         action { [:SEMICOLON, text] }

      when (text = @ss.scan(/\w(\w|\d)*/))
         action { [:NAME, text] }

      when (text = @ss.scan(/\w+/))
         action { [:WORD, text] }

      when (text = @ss.scan(/[\n]/))
         action {} # no action

      when (text = @ss.scan(/./))
         action { [:TEXT, text] }

      else
        text = @ss.string[@ss.pos .. -1]
        raise  ScanError, "can not match: '" + text + "'"
      end  # if

    else
      raise  ScanError, "undefined state: '" + state.to_s + "'"
    end  # case state
    token
  end  # def _next_token

end # class
