#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require './compiler.rex.rb'
 
class CompilerLanguage < Racc::Parser

module_eval(<<'...end compiler.y/module_eval...', 'compiler.y', 32)
  def parse(input)
    scan_str(input)
  end
...end compiler.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    26,    36,    34,    33,    10,    17,    28,    53,    24,    55,
    22,    30,    41,    26,    26,    26,    26,    18,    21,    28,
    28,    28,    28,    31,    27,    44,    45,    46,    48,    49,
    50,    37,    38,    39,    40,    42,    43,    27,    27,    27,
    27,    60,    20,    59,    16,    14,    44,    45,    46,    48,
    49,    50,    37,    38,    39,    40,    42,    43,    57,   -11,
    62,    63,    13,    44,    45,    46,    48,    49,    50,    37,
    38,    39,    40,    42,    43,    54,    65,   nil,   nil,   nil,
    44,    45,    46,    48,    49,    50,    37,    38,    39,    40,
    42,    43,    17,     3,   nil,     5,   nil,     7,   nil,     8,
    10,   nil,   nil,   nil,    18,    44,    45,    46,    48,    49,
    50,    37,    38,    39,    40,    42,    43,     3,   nil,     5,
   nil,     7,   nil,     8,    10,     3,   nil,     5,   nil,     7,
   nil,     8,    10,     3,   nil,     5,   nil,     7,   nil,     8,
    10 ]

racc_action_check = [
    22,    24,    21,    20,    18,     6,    22,    31,    15,    36,
    10,    19,    25,    28,    16,    53,    47,     6,     9,    28,
    16,    53,    47,    19,    22,    25,    25,    25,    25,    25,
    25,    25,    25,    25,    25,    25,    25,    28,    16,    53,
    47,    58,     7,    54,     5,     4,    58,    58,    58,    58,
    58,    58,    58,    58,    58,    58,    58,    58,    51,     3,
    60,    61,     1,    51,    51,    51,    51,    51,    51,    51,
    51,    51,    51,    51,    51,    35,    64,   nil,   nil,   nil,
    35,    35,    35,    35,    35,    35,    35,    35,    35,    35,
    35,    35,    29,    12,   nil,    12,   nil,    12,   nil,    12,
    12,   nil,   nil,   nil,    29,    56,    56,    56,    56,    56,
    56,    56,    56,    56,    56,    56,    56,    59,   nil,    59,
   nil,    59,   nil,    59,    59,    62,   nil,    62,   nil,    62,
   nil,    62,    62,     0,   nil,     0,   nil,     0,   nil,     0,
     0 ]

racc_action_pointer = [
   131,    59,   nil,    44,    30,    39,     3,    38,   nil,    18,
     0,   nil,    91,   nil,   nil,     4,    10,   nil,    -5,     9,
     0,     2,    -4,   nil,    -4,     9,   nil,   nil,     9,    90,
   nil,    -3,   nil,   nil,   nil,    64,     2,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    12,   nil,   nil,
   nil,    47,   nil,    11,    31,   nil,    89,   nil,    30,   115,
    48,    48,   123,   nil,    63,   nil ]

racc_action_default = [
   -35,   -35,    -7,    -3,   -35,   -35,   -35,   -35,   -10,   -35,
   -35,    -1,   -35,    -4,   -18,   -35,   -35,   -15,   -35,   -35,
   -35,   -35,   -35,    -2,    -9,   -35,   -31,   -32,   -35,   -35,
   -17,   -35,   -12,    -6,    66,   -35,   -35,   -25,   -26,   -27,
   -28,    -5,   -29,   -30,   -19,   -20,   -21,   -35,   -22,   -23,
   -24,   -35,   -14,   -35,   -35,    -8,   -33,   -34,   -35,   -35,
   -35,   -35,   -35,   -13,   -35,   -16 ]

racc_goto_table = [
    11,    25,    19,    15,    29,     9,    32,    35,   nil,   nil,
   nil,   nil,    23,    51,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    52,   nil,   nil,   nil,   nil,
   nil,   nil,    56,   nil,   nil,   nil,   nil,   nil,    58,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    61,
   nil,   nil,    64 ]

racc_goto_check = [
     2,     5,    10,     8,     9,     1,    11,     5,   nil,   nil,
   nil,   nil,     2,     5,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    10,   nil,   nil,   nil,   nil,
   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,     5,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,
   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     5,     0,   nil,   nil,   -15,   nil,   nil,    -1,   -14,
    -4,   -13,   nil ]

racc_goto_default = [
   nil,   nil,   nil,    12,     1,   nil,     2,     4,   nil,     6,
   nil,   nil,    47 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 30, :_reduce_none,
  2, 31, :_reduce_none,
  1, 31, :_reduce_none,
  2, 32, :_reduce_none,
  4, 32, :_reduce_none,
  3, 32, :_reduce_none,
  1, 32, :_reduce_none,
  5, 33, :_reduce_none,
  3, 33, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  3, 35, :_reduce_none,
  7, 38, :_reduce_none,
  3, 39, :_reduce_none,
  1, 39, :_reduce_none,
  7, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 37, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  3, 34, :_reduce_none,
  3, 34, :_reduce_none ]

racc_reduce_n = 35

racc_shift_n = 66

racc_token_table = {
  false => 0,
  :error => 1,
  "" => 2,
  :SEMICOLON => 3,
  :NAME => 4,
  :EQUALS => 5,
  :RETURN => 6,
  :EXPR => 7,
  :CONST => 8,
  :IF => 9,
  :OPEN_PAREN => 10,
  :CLOSE_PAREN => 11,
  :OPEN_CURLY => 12,
  :CLOSE_CURLY => 13,
  :ELSE => 14,
  :INT => 15,
  :NOT_EQUALS => 16,
  :EQUALS_EQUALS => 17,
  :LESS_EQUALS => 18,
  :GREATER_EQUALS => 19,
  :GREATER => 20,
  :LESS => 21,
  :PLUS => 22,
  :MINUS => 23,
  :MULTIPLY => 24,
  :DIVIDE => 25,
  :RIGHT_BIT_SHIFT => 26,
  :LEFT_BIT_SHIFT => 27,
  :NUMBER => 28 }

racc_nt_base = 29

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"\"",
  "SEMICOLON",
  "NAME",
  "EQUALS",
  "RETURN",
  "EXPR",
  "CONST",
  "IF",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "ELSE",
  "INT",
  "NOT_EQUALS",
  "EQUALS_EQUALS",
  "LESS_EQUALS",
  "GREATER_EQUALS",
  "GREATER",
  "LESS",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "RIGHT_BIT_SHIFT",
  "LEFT_BIT_SHIFT",
  "NUMBER",
  "$start",
  "start",
  "stmts",
  "stmt",
  "decl",
  "expr",
  "ifblock",
  "modifier",
  "type",
  "if",
  "elsif",
  "else",
  "infix" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class CompilerLanguage
